name: '[CD.DeployPages]'

on:
  push:
      - '*'

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    working-directory: 
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - run: cd app

      - name: Generate your content
        run: yarn
      
      - run: yarn build

      - name: publish to pages
        uses: rayluo/github-pages-overwriter@v1.3

        with:
          source-directory: ./app
          target-branch: gh-pages