name: '[CD] DeployPages'

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: yarn install
        working-directory: app
        run: yarn
      
      - name: build
        working-directory: app
        run: yarn build

      - name: publish to pages
        uses: rayluo/github-pages-overwriter@v1.3

        with:
          source-directory: pages
          target-branch: pages